name: agromanagement
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11.8
  - black
  - gdal
  - geopandas
  - ipykernel
  - isort
  - pytest
  - pylint
  - pip
  - psycopg2
  - pyproj
  - pyyaml
  - pip:
    - cdsetool
    - rasterio[s3]
    - sat-search
