name: agromanagement
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11.8
  - black
  - gdal
  - geopandas
  - ipykernel
  - isort
  - pandas
  - pytest
  - pylint
  - pip
  - psycopg2
  - pyproj
  - pyyaml
  - pip:
    # - boto3
    # - cdsapi
    - cdsetool
    # - rasterio[s3]
    # - sat-search
